import type { NextPage } from 'next'
import Head from 'next/head'
import { Link, Typography } from '@mui/material'
import { Box } from '@mui/system'
import Header from '../components/common/Header'
import Footer from '../components/common/Footer'
import Card from '../components/home/Card'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
	return (
		<Box className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
			</Head>

			<Header />
			<main className={styles.main}>
				<Typography
					component="h1"
					variant="h1"
					className={styles.title}
				>
					Welcome to <Link href="https://nextjs.org">Next.js!</Link>
				</Typography>

				<Typography
					component="p"
					variant="subtitle1"
					className={styles.description}
				>
					Get started by editing{' '}
					<Box component="code" className={styles.code} sx={{ display: 'inline' }}>pages/index.tsx</Box>
				</Typography>

				<Box className={styles.grid}>
					<Card
						url="https://nextjs.org/docs"
						title="Documentation"
					>
						Find in-depth information about Next.js features and API.
					</Card>

					<Card
						url="https://nextjs.org/learn"
						title="Learn"
					>
						Learn about Next.js in an interactive course with quizzes!
					</Card>

					<Card
						url="https://github.com/vercel/next.js/tree/master/examples"
						title="Examples"
					>
						Discover and deploy boilerplate example Next.js projects.
					</Card>

					<Card
						url="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
						title="Deploy"
					>
						Instantly deploy your Next.js site to a public URL with Vercel.
					</Card>

					<Card
						url="/chart"
						title="Chart"
					>
						Use DevExtreme REACTIVE Chart.
					</Card>
				</Box>
			</main>

			<Footer />
		</Box>
	)
}

export default Home
