import type { NextPage } from 'next'
import Head from 'next/head'
import { Link, Paper, Typography } from '@mui/material'
import { Box } from '@mui/system'
import Header from '../components/common/Header'
import Footer from '../components/common/Footer'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
	return (
		<Box className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
			</Head>

			<Header />
			<main className={styles.main}>
				<Typography
					component="h1"
					variant="h1"
					className={styles.title}
				>
					Welcome to <Link href="https://nextjs.org">Next.js!</Link>
				</Typography>

				<Typography
					component="p"
					variant="subtitle1"
					className={styles.description}
				>
					Get started by editing{' '}
					<Box component="code" className={styles.code} sx={{ display: 'inline' }}>pages/index.tsx</Box>
				</Typography>

				<Box className={styles.grid}>
					<Paper
						component="a"
						href="https://nextjs.org/docs"
						variant="outlined"
						className={styles.card}
					>
						<Typography component="h2" sx={{ fontWeight: 'bold' }}>
							Documentation &rarr;
						</Typography>
						<Typography component="p">
							Find in-depth information about Next.js features and API.
						</Typography>
					</Paper>

					<Paper
						component="a"
						href="https://nextjs.org/learn"
						variant="outlined"
						className={styles.card}
					>
						<Typography component="h2" sx={{ fontWeight: 'bold' }}>
							Learn &rarr;
						</Typography>
						<Typography component="p">
							Learn about Next.js in an interactive course with quizzes!
						</Typography>
					</Paper>

					<Paper
						component="a"
						href="https://github.com/vercel/next.js/tree/master/examples"
						variant="outlined"
						className={styles.card}
					>
						<Typography component="h2" sx={{ fontWeight: 'bold' }}>
							Examples &rarr;
						</Typography>
						<Typography component="p">
							Discover and deploy boilerplate example Next.js projects.
						</Typography>
					</Paper>

					<Paper
						component="a"
						href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
						variant="outlined"
						className={styles.card}
					>
						<Typography component="h2" sx={{ fontWeight: 'bold' }}>
							Deploy &rarr;
						</Typography>
						<Typography component="p">
							Instantly deploy your Next.js site to a public URL with Vercel.
						</Typography>
					</Paper>

					<Paper
						component="a"
						href="/chart"
						variant="outlined"
						className={styles.card}
					>
						<Typography component="h2" sx={{ fontWeight: 'bold' }}>
							Chart &rarr;
						</Typography>
						<Typography component="p">
							Use DevExtreme REACTIVE Chart.
						</Typography>
					</Paper>
				</Box>
			</main>

			<Footer />
		</Box>
	)
}

export default Home
